name: main_flow
on:
  schedule:
    - cron: '30 5 * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Python dependencies
        run: |
          pip install -U prefect==2.*
          pip install -r requirements.txt
      - name: Prefect Cloud login
        run: |
          prefect config set PREFECT_API_KEY=${{secrets.PREFECT_API_KEY}} 
          prefect cloud workspace set --workspace "${{secrets.PREFECT_WORKSPACE}}"
      - name: main_flow
        run: |
          export PYTHONPATH="${PYTHONPATH}:/home/runner/work/prefect-getting-started/prefect-getting-started/"
          python flows/main_flow.py
      
      
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@users.noreply.github.com"

      - name: Create and save file
        run: |
          echo "Timestamp: $(date)" > gemeindeabdeckung.csv
          git add gemeindeabdeckung.csv
          git commit -m "Add timestamp file"
          git push
