name: Run flow
on:
  workflow_dispatch:
    inputs:
      prefect-version:
        description: Prefect version for flows
        required: true
        default: '2.*'
        type: string
      flow:
        description: Flow to run
        required: true
        type: choice
        options: ['main_flow.py']
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
          
      - name: Python dependencies
        run: |
          pip install -U prefect==2.*
          pip install -r requirements.txt
      - name: Prefect Cloud login
        run: |
          prefect config set PREFECT_API_KEY=${{secrets.PREFECT_API_KEY}} 
          prefect cloud workspace set --workspace "${{secrets.PREFECT_WORKSPACE}}"
      - name: Google Credentials
        run: |
          pip install google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client pandas gspread gspread_dataframe

      - name: Set up Google API credentials
        env:
          GOOGLE_CREDENTIALS_BASE64: ${{ secrets.GOOGLE_CREDENTIALS_BASE64 }}
        run: |
          echo "GOOGLE_APPLICATION_CREDENTIALS=$(echo "$GOOGLE_CREDENTIALS_BASE64" | base64 --decode)" >> $GITHUB_ENV
      - name: main_flow
        run: |
          export PYTHONPATH="${PYTHONPATH}:/home/runner/work/prefect-getting-started/prefect-getting-started/"
          python flows/main_flow.py
